spring:
  datasource:
    username: h
    password: wori2251013@

    url: jdbc:mysql://localhost:3306/foodorderdb
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
